name: Fetch FX Data

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:          # also allow manual trigger from GitHub UI

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests

      - name: Run fetcher
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: python fetch_data.py

      - name: Commit updated database
        run: |
          git config user.name  "fxlens-bot"
          git config user.email "bot@fxlens"
          git add data/fx_data.db
          git diff --staged --quiet || git commit -m "data: auto-update $(date -u +%Y-%m-%dT%H:%M)"
          git push
